// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rughtylqssftfcfljwcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1Z2h0eWxxc3NmdGZjZmxqd2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjY0ODYsImV4cCI6MjA2NTUwMjQ4Nn0.P2D4nPerfXPf0APmtcZLd2GEs7zCXe5Pvb9ps5M_Uvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);